before_script:
  - echo 'start'
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - echo 'Preparation done !'

doc:
  script:
    - ls -l
    - make html